pagopa/io-functions-cgn

CODEOWNERS
models/user_cgn.ts
openapi/index.yaml
package.json
yarn.lock

This PR adds `UserCgn` definition form scratch, in order to model:
- The CGN owner expressed as a `FiscalCode`
- The status of the CGN that could be PENDING, ACTIVATED, REVOKED, CANCELED

[#175906146] create user cgn model

---

GetCgnStatus/__tests__/handler.test.ts
__mocks__/mock.ts
openapi/index.yaml

- Add info about issued Date and expiration Date
An `Activated` CGN must have the informations related to:
- Issued Date
- Expiration Date
It has been tested by performing unit tests.

[#175896826] Add more info on Activated cgn status

---

GetCgnStatus/__tests__/handler.test.ts
openapi/index.yaml

- Add info about revokation Date and motivation
A `Revoked` CGN must have the informations related to:
- Revokation Date
- Motivation ( of the revokation )
It has been tested by performing unit tests.

[#175908859] Add revokation attributes on CGN Status

---

SendMessageActivity/__tests__/handler.test.ts
SendMessageActivity/function.json
SendMessageActivity/handler.ts
SendMessageActivity/index.ts
__mocks__/durable-functions.ts
env.example
utils/appinsights.ts
utils/fetch.ts
utils/hash.ts
utils/notifications.ts

- Add a `SendMessageActivity`
- Add Application Insights utility
- Add `fetch` utility
A CGN' status change must be followed by sending an in APP message that allows citizen to be notified about status change.
It has been tested by performing unit tests.

[#175908683] Add Send Message activity

---

package.json
tsconfig.json
yarn.lock

In order to avoid inconsistency between standard build and prod one, added a postbuild check to identify missing dependencies in package.json

[#177037990] Fixed second-level dependencies

---

host.json

Adding `"localRpcEndpointEnabled": false` for fix testing purpose.

disable_local_rpc_endpoint_for_load_tests

---

GenerateOtp/index.ts
GetCgnActivation/index.ts
GetCgnStatus/index.ts
GetEycaActivation/index.ts
GetEycaStatus/index.ts
Info/index.ts
StartCgnActivation/index.ts
StartEycaActivation/index.ts
UpsertCgnStatus/index.ts
package.json
yarn.lock

Update from io-functions-express to @pagopa/express-azure-functions 2.0.0

[#178017887] update to @pagopa/express-azure-functions

---

host.json

change durable function storage (change connection string to DURABLE_FUNCTION_STORAGE_CONNECTION_STRING)
close internet access to durable function storage

[Remade from balanza:patch1] Change durable function storage

---

UpdateExpiredCgn/handler.ts
UpdateExpiredEyca/handler.ts
utils/orchestrators.ts

This PR enables CF obfuscation on orchestrators identifier
- makeOrchestratorId utility now performs Cf hash
Due to privacy needs we must obfuscate fiscalCodes on orchestrator identifiers
unit

[#IC-213] Obfuscate CF on orchestrator ids

---

utils/messages.ts

This PR enables CTA on CGN activation messages
- `messages` added cta frontmatter
This is needed to enable cta while opening CGN' activation flow messages

[#IC-217] Add cta to messages

---

DeleteCgnActivity/__tests__/handler.test.ts
DeleteCgnActivity/handler.ts
DeleteEycaActivity/__tests__/handler.test.ts
DeleteEycaActivity/handler.ts
DeleteLegalDataBackupActivity/__tests__/handler.test.ts
DeleteLegalDataBackupActivity/handler.ts
ExpireEycaOrchestrator/index.ts
StartCgnActivation/__tests__/handler.test.ts
StartCgnActivation/handler.ts
models/__tests__/user_cgn.test.ts
models/user_card_versionend_deletable.ts
models/user_cgn.ts
models/user_eyca_card.ts

[#IC-219] Fix findAll on card unsubscription

---

DeleteCardActivation/__test__/handler.test.ts
DeleteCardActivation/handler.ts
models/user_card_versionend_deletable.ts
models/user_cgn.ts
models/user_eyca_card.ts

hotfix delete & findAll

---

DeleteCgnExpirationActivity/__test__/handler.test.ts
DeleteCgnExpirationActivity/handler.ts
DeleteCgnExpirationActivity/index.ts
DeleteEycaExpirationActivity/__test__/handler.test.ts
DeleteEycaExpirationActivity/handler.ts
DeleteEycaExpirationActivity/index.ts
utils/table_storage.ts

Add expirationDate as partitionKey on expiration delete
This PR is needed because table entry delete fails without partition key

[#IC-220] Add partition key to Expiration delete

---

GetCgnActivation/handler.ts
UpdateExpiredEyca/function.json
utils/errors.ts

[#IC-222] rename failures and add tracking for orchestration terminate

---

UpdateCgnOrchestrator/handler.ts
utils/eyca.ts

Refactor permanent to transient failure on decoding error

---

host.json

Add AppInsights host sampling settings

---

DeleteCardActivation/handler.ts
DeleteEycaActivity/__tests__/handler.test.ts
DeleteEycaActivity/handler.ts
DeleteEycaExpirationActivity/handler.ts
utils/__tests__/table_storage.test.ts
utils/table_storage.ts

This PR fixes a possible failure in card delete if expiration tuple does not exists
Add skip for 404 if expiration tuple does not exists

[#IC-331] - Skip Expiration delete if tuple does not exists

---

DeleteCardActivation/handler.ts
DeleteCgnOrchestratorV2/__tests__/handler.test.ts
DeleteCgnOrchestratorV2/function.json
DeleteCgnOrchestratorV2/handler.ts
DeleteCgnOrchestratorV2/index.ts

- Add DeleteCgnOrchestratorV2
- DeleteCardActivation now points to brand new Delete Orchestrator version (v2)
This PR is needed by legal in order to not track users that wants to unsubscribe to CGN. 
Unit tests

[#IC-344] Remove Legal Backup from Card unsubscription

---

host.json

Reduce Log level to Info

---

.devops/code-review-pipelines.yml
.devops/deploy-pipelines.yml
.vscode/settings.json
docker-compose.yml
docker/functions/Dockerfile
host.json
package.json
yarn.lock

This PR depends on https://github.com/pagopa/io-infra/pull/304
* edited `Dockerfile` to support runtime v4
* edited pipelines
* updated `durable-functions` and `@azure/functions` dependencies
* edited `docker-compose.yml`
support azure functions runtime v4
lint, build and tests passed

[#IOCIT-175] add functions runtime v4 support

---

.devops/code-review-pipelines.yml
.eslintrc.js
.funcignore
.github/workflows/pr-title-linter-and-linker.yaml
Dangerfile.ts
package.json
tsconfig.json
yarn.lock

* [Remove Dangerfile.ts](https://github.com/pagopa/io-functions-cgn/commit/fe445a083dfd2853aa5a9f71db9b30d9f2d2d567);
* [Remove danger job from pipeline](https://github.com/pagopa/io-functions-cgn/commit/ddf3fbace8fd3943716b0f15ac96492074c55236);
* [Remove danger plugins](https://github.com/pagopa/io-functions-cgn/commit/aec6845944d9576cf3ba46855c62db94a3b19e08);
* [Add github action](https://github.com/pagopa/io-functions-cgn/commit/2829ad16bd63f64aa5ae18d9760ab10a78b64fbc);
* [Remove danger refs](https://github.com/pagopa/io-functions-cgn/commit/445c1eb5a7d4e157e18eecb3c3c4fef840f6b864);
Replace Danger in favour of a github action.

[#ICC-336] Replace danger with github action

---

utils/messages.ts

Changed copy for:
- activation message
- problem message
We need a revamp of the content.

[PE-642] Changed messages copy
